### ISSUE TITLE
ADD: support for password inputs

### ISSUE THREAD

**Issue by Uzay-G** [fredrik-corneliusson/click-web#6]
Could be cool to implement password inputs, like [here](https://click.palletsprojects.com/en/7.x/options/#password-prompts).

I'm going to see if I can figure it out looking at the click_inputs file

**Comment by fredrik-corneliusson** [comment]
Sounds great,
Will probably be hard to support the interactive prompt feature in click as the actual click process is just initialized with the arguments and the stdout is just streamed to the web process.
If you are ok with just having an password field in the browser take a look at how EmailInput is done.
https://github.com/fredrik-corneliusson/click-web/blob/master/click_web/resources/input_fields.py#L252

You can probably do something similar but instead of type_attrs['type'] = 'email' use  type_attrs['type'] = 'password'

**Comment by fredrik-corneliusson** [comment]
Sorry for the late reply.
Sure, that would be great.

**Comment by fredrik-corneliusson** [comment]
Now implemented.

**Comment by Uzay-G** [comment]
Nice!
